--- #YAML:1.0
name:               WSDL-Compile
version:            0.01_1
abstract:           Compile SOAP WSDL from your Moose classes.
author:
    - Alex J. G. Burzyński <ajgb@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:         0
    Moose:                0.93
    MooseX::Types::XMLSchema:  0
    Perl6::Junction:      1.40000
    Test::More:           0
    XML::Compile::SOAP:   2.08
    XML::LibXML:          1.69
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
